services:
  portainer:
    container_name: portainer
    build:
      dockerfile: Dockerfile
    ports:
      - 9000:9000
      - 9433:9433
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always